### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by defvayne23** [Monkee-Boy/generator-mboy-deploy#1]
When asking if using www or root domain, add a 3rd option that allows me to enter my own subdomain.

**Comment by fleeting** [comment]
@defvayne23 How should it handle the dev path in that case? If the production path ends up being `/var/www/domain.com/blog` (blog.domain.com) should the dev path just be `/var/www/domain.com/blog/dev` (dev.blog.domain.com)?

**Comment by defvayne23** [comment]
I think the best way would be to create blog-dev, dev.blog, or blog.dev.

On Monday, February 9, 2015, James Fleeting notifications@github.com
wrote:

> @defvayne23 https://github.com/defvayne23 How should it handle the dev
> path in that case? If the production path ends up being /var/www/
> domain.com/blog (blog.subdomain.com) should the dev path just be /var/www/
> domain.com/blog/dev (dev.blog.subdomain.com)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Monkee-Boy/generator-mboy-deploy/issues/1#issuecomment-73606468
> .

## 

John Hoover  •  Web Developer  •  Monkee-Boy
9390 Research Blvd, Bldg. II, Suite 425, Austin, TX 78759

## john@monkee-boy.com | 512.335.2221 ext 133

_Need Help? No problem -- simply send an email to help@monkee-boy.com
help@monkee-boy.com with your instructions, attachments, etc. and a
Monkee-Ticket will automatically be created._

**Comment by fleeting** [comment]
I'm going to go with `dev.blog.domain.com` as the default.
